### ISSUE TITLE
Contact Refinement Parallax Mapping

### ISSUE THREAD

**Issue by BlueAmulet** [orels1/orels-Unity-Shaders#42]
**Describe what are you aiming to achieve**
Contact Refinement Parallax Mapping is a technique that's supposed to help avoid the pancaking effect

Example from the linked blog post below (32 steps for all):
![](https://cdnb.artstation.com/p/media_assets/images/images/000/448/817/large/M_Comparison.jpg)

**Describe any workarounds you can use now**
N/A

**Any other comments or context/references**
Blog Post:
[A new approach for Parallax Mapping: presenting the Contact Refinement Parallax Mapping Technique](https://www.artstation.com/blogs/andreariccardi/3VPo/a-new-approach-for-parallax-mapping-presenting-the-contact-refinement-parallax-mapping-technique)
Unity 2018 Shader Code:
[ParallaxOcclusionMapping.cginc](https://github.com/a-riccardi/shader-toy/blob/master/ShaderToy/Assets/Shaders/ParallaxOcclusionMapping.cginc)

**Comment by orels1** [comment]
Ooh, interesting!
My shader uses a fairly common POM implementation which generally seems to give OK results.
I'll look at this and see how it compares performance-wise too! Thank you for the suggestion

**Comment by orels1** [comment]
Moved this here due to issues with my linear sync integration: https://github.com/orels1/orels-Unity-Shaders/issues/42

This will be properly tracked in my actual task tracker
